# Question (1)

In [3]:
import numpy as np
np.__version__

'1.20.3'

# Question (2)

In [4]:
import pandas as pd
pd.__version__

'1.3.2'

# Question (3)¶

In [7]:
df = pd.read_csv('data.csv') 
df.groupby('Make').MSRP.mean().round(2)

Make
Acura              34887.59
Alfa Romeo         61600.00
Aston Martin      197910.38
Audi               53452.11
BMW                61546.76
Bentley           247169.32
Bugatti          1757223.67
Buick              28206.61
Cadillac           56231.32
Chevrolet          28350.39
Chrysler           26722.96
Dodge              22390.06
FIAT               22670.24
Ferrari           238218.84
Ford               27399.27
GMC                30493.30
Genesis            46616.67
HUMMER             36464.41
Honda              26674.34
Hyundai            24597.04
Infiniti           42394.21
Kia                25310.17
Lamborghini       331567.31
Land Rover         67823.22
Lexus              47549.07
Lincoln            42839.83
Lotus              69188.28
Maserati          114207.71
Maybach           546221.88
Mazda              20039.38
McLaren           239805.00
Mercedes-Benz      71476.23
Mitsubishi         21240.54
Nissan             28583.43
Oldsmobile         11542.54
Plymouth       

# Question (4)

In [8]:
df["Engine HP"].loc[df["Year"]>=2015].isnull().sum()

51

# Question (5)

In [15]:
avg_Engine_nofill = df["Engine HP"].mean()
print (round (avg_Engine_nofill ))

249


In [14]:
mean_fill = df["Engine HP"].fillna(avg_Engine_nofill)
avg_Engine_fill = mean_fillna.mean()
print (round (avg_Engine_fill))

249


# Question (6)

In [16]:
dropped_duplicate = df[df["Make"]=="Rolls-Royce"][["Engine HP","Engine Cylinders","highway MPG"]].drop_duplicates()
dropped_duplicate

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5279       563.0              12.0           20
7443       322.0              12.0           15
7553       453.0              12.0           19
11448      624.0              12.0           21

In [17]:
X = dropped_duplicate.values
X

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [18]:
XTX = X.T @ X
XTX

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [19]:
inv_XTX = np.linalg.inv(XTX)
inv_XTX

array([[ 5.17815728e-05,  9.06587044e-04, -1.92984188e-03],
       [ 9.06587044e-04,  1.05723058e-01, -8.87084092e-02],
       [-1.92984188e-03, -8.87084092e-02,  1.05900809e-01]])

In [20]:
inv_XTX.sum()

0.032212320677486195

# Question (7)

In [21]:
y = np.array([1000, 1100, 900, 1200, 1000, 850, 1300])
y

array([1000, 1100,  900, 1200, 1000,  850, 1300])

In [23]:
g = inv_XTX @ X.T 
g

array([[-0.00486592,  0.00336507, -0.00049461,  0.00143523, -0.00139492,
        -0.0023309 ,  0.00266407],
       [-0.19020088,  0.09362543, -0.08379139,  0.00491702,  0.22997159,
        -0.00609915, -0.02848958],
       [ 0.25164625, -0.13888652,  0.0729151 , -0.03298571, -0.09739786,
         0.07339609, -0.04480526]])

In [24]:
w = g.dot(y)
w

array([ 0.19989598, 31.02612262, 31.65378877])

In [25]:
w[0]

0.19989598183186175